### ISSUE TITLE
repo is failing due to python2 syntax (wants python 3.6+) ???

### ISSUE THREAD

**Issue by bvacaliuc** [uvdl/yocto-ornl#45]
```
mkdir -p /tmp/yocto-ornl-thud
cd /tmp/yocto-ornl-thud && \
	/usr/local/bin/repo init -u https://github.com/varigit/variscite-bsp-platform.git -b thud && \
	/usr/local/bin/repo sync -j32
repo: warning: Python 2 is no longer supported; Please upgrade to Python 3.6+.
Downloading Repo source from https://gerrit.googlesource.com/git-repo
remote: Counting objects: 1, done
remote: Finding sources: 100% (30/30)
remote: Total 30 (delta 9), reused 30 (delta 9)
Unpacking objects: 100% (30/30), done.
Traceback (most recent call last):
  File "/tmp/yocto-ornl-thud/.repo/repo/main.py", line 56, in <module>
    from subcmds.version import Version
  File "/tmp/yocto-ornl-thud/.repo/repo/subcmds/__init__.py", line 38, in <module>
    ['%s' % name])
  File "/tmp/yocto-ornl-thud/.repo/repo/subcmds/upload.py", line 27, in <module>
    from hooks import RepoHook
  File "/tmp/yocto-ornl-thud/.repo/repo/hooks.py", line 472
    file=sys.stderr)
        ^
SyntaxError: invalid syntax
Makefile:71: recipe for target '/tmp/yocto-ornl-thud/setup-environment' failed
make[1]: *** [/tmp/yocto-ornl-thud/setup-environment] Error 1
Makefile:108: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by waddle77** [comment]
Obsolete.  We now use Python2 meta layer.
